export enum USER_ERROR_ENUM {
  CONFIRM_PASSWORD_NOT_MATCH = 'CONFIRM_PASSWORD_NOT_MATCH',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  NOT_FOUND = 'NOT_FOUND',
}
